CREATE TABLE ECALPEDESTALS ( IOV_VALUE_ID UNSIGNEDLONG , TIME UNSIGNEDLONG , PRIMARY KEY(IOV_VALUE_ID) );

CREATE TABLE ECALPEDESTALS_ITEM ( POS UNSIGNEDLONG  NOT NULL,IOV_VALUE_ID UNSIGNEDLONG  NOT NULL,MEAN_X1 FLOAT  NOT NULL,MEAN_X12 FLOAT  NOT NULL,MEAN_X6 FLOAT  NOT NULL,RMS_X1 FLOAT  NOT NULL,RMS_X12 FLOAT  NOT NULL,RMS_X6 FLOAT  NOT NULL,DET_ID UNSIGNEDINT  NOT NULL, PRIMARY KEY(IOV_VALUE_ID,POS), FOREIGN KEY(IOV_VALUE_ID) REFERENCES ECALPEDESTALS(IOV_VALUE_ID) );

CREATE TABLE POOL_OR_MAPPING_COLUMNS ( VERSION TEXT  NOT NULL,SCOPE_NAME TEXT  NOT NULL,VARIABLE_NAME TEXT  NOT NULL,COLUMN_NAME TEXT  NOT NULL,POSITION INT  NOT NULL );

CREATE TABLE POOL_OR_MAPPING_ELEMENTS ( ELEMENT_TYPE TEXT  NOT NULL,SCOPE_NAME TEXT  NOT NULL,VARIABLE_NAME TEXT  NOT NULL,VARIABLE_TYPE TEXT  NOT NULL,TABLE_NAME TEXT  NOT NULL,VERSION TEXT  NOT NULL );

CREATE TABLE POOL_OR_MAPPING_VERSIONS ( MAPPING_VERSION TEXT  NOT NULL, UNIQUE ( MAPPING_VERSION ) );

insert into ECALPEDESTALS(IOV_VALUE_ID,TIME) values(0, 5);
insert into ECALPEDESTALS(IOV_VALUE_ID,TIME) values(1, 10);
insert into ECALPEDESTALS_ITEM( POS,IOV_VALUE_ID,MEAN_X1,MEAN_X12,MEAN_X6,RMS_X1,RMS_X12,RMS_X6,DET_ID) values(0, 0, 1.1,1.12,1.06,0.1,0.12,0.6,1234);
insert into ECALPEDESTALS_ITEM( POS,IOV_VALUE_ID,MEAN_X1,MEAN_X12,MEAN_X6,RMS_X1,RMS_X12,RMS_X6,DET_ID) values(1, 0, 1.1,1.12,1.06,0.1,0.12,0.6,1235);
insert into ECALPEDESTALS_ITEM( POS,IOV_VALUE_ID,MEAN_X1,MEAN_X12,MEAN_X6,RMS_X1,RMS_X12,RMS_X6,DET_ID) values(2, 0, 1.1,1.12,1.06,0.1,0.12,0.6,1236);
insert into ECALPEDESTALS_ITEM( POS,IOV_VALUE_ID,MEAN_X1,MEAN_X12,MEAN_X6,RMS_X1,RMS_X12,RMS_X6,DET_ID) values(0, 1, 1.1,1.12,1.06,0.1,0.12,0.6,1234);
insert into ECALPEDESTALS_ITEM( POS,IOV_VALUE_ID,MEAN_X1,MEAN_X12,MEAN_X6,RMS_X1,RMS_X12,RMS_X6,DET_ID) values(1, 1, 1.1,1.12,1.06,0.1,0.12,0.6,1235);
insert into ECALPEDESTALS_ITEM( POS,IOV_VALUE_ID,MEAN_X1,MEAN_X12,MEAN_X6,RMS_X1,RMS_X12,RMS_X6,DET_ID) values(2, 1, 1.1,1.12,1.06,0.1,0.12,0.6,1236);
